"""add index_update table

Revision ID: 0928999bac08
Revises: 2e4d256a59c2
Create Date: 2026-05-31 02:26:47.492715

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0928999bac08"
down_revision: Union[str, Sequence[str], None] = "2e4d256a59c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "index_update",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("lease_id", sa.Integer(), nullable=False),
        sa.Column("application_date", sa.Date(), nullable=False),
        sa.Column("previous_rent", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("new_rent", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("index_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("index_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["lease_id"],
            ["lease.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("index_update")
    # ### end Alembic commands ###
