"""add bank_movement and reconciliation tables

Revision ID: 1c44557ef4b6
Revises: e1cd76ded677
Create Date: 2026-05-31 13:11:32.908441

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c44557ef4b6"
down_revision: Union[str, Sequence[str], None] = "e1cd76ded677"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_movement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("concept", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("iban_origin", sqlmodel.sql.sqltypes.AutoString(length=34), nullable=True),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("raw_data", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reconciliation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("bank_movement_id", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["bank_movement_id"],
            ["bank_movement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bank_movement_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reconciliation")
    op.drop_table("bank_movement")
    # ### end Alembic commands ###
