"""add expense table

Revision ID: e1cd76ded677
Revises: bc191700d28c
Create Date: 2026-05-31 13:09:43.026644

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1cd76ded677"
down_revision: Union[str, Sequence[str], None] = "bc191700d28c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("property_id", sa.Integer(), nullable=False),
        sa.Column("lease_id", sa.Integer(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("deductible", sa.Boolean(), nullable=False),
        sa.Column("supplier", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("invoice_number", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["lease_id"],
            ["lease.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expense")
    # ### end Alembic commands ###
